/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import pack.AbstractCalculator;
import pack.CustomDictionaryCalc;
import pack.DefaultDictionaryCalc;
import pack.InputFileConfigurator;
import pack.Text;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Milica
 */
public class CalculatorForm extends JFrame {

    /**
     * Creates new form CalculatorForm
     */
    public CalculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtInputFilePath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtOutputFolderPath = new javax.swing.JTextField();
        jTxtDictFilePath = new javax.swing.JTextField();
        jTxtOutputFileName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnCalculate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Linguistic Metrics Calculator");

        jLabel1.setText("Enter the input file path in this form D:\\directory\\subdirectory\\filename.txt: ");

        jTxtInputFilePath.setText(" ");

        jLabel2.setText("Enter the output folder path in this form D:\\directory\\subdirectory:");

        jTxtOutputFolderPath.setText(" ");

        jTxtDictFilePath.setText(" ");

        jTxtOutputFileName.setText(" ");

        jLabel3.setText("If you want to use a custom dictionary, enter the dictionary file path in this form");

        jLabel4.setText("Enter the output file name:");

        jbtnCalculate.setText("Calculate!");
        jbtnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalculateActionPerformed(evt);
            }
        });

        jLabel5.setText("D:\\directory\\subdirectory\\dictname.txt:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtOutputFolderPath, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtInputFilePath, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTxtDictFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtOutputFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jbtnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jTxtInputFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtOutputFolderPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtDictFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtOutputFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jbtnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalculateActionPerformed
        String inFilePath = jTxtInputFilePath.getText().trim();
        String outFolderPath = jTxtOutputFolderPath.getText().trim();
	String dictPath = jTxtDictFilePath.getText().trim();
	String resName = jTxtOutputFileName.getText().trim();
        Text t; 
        try{
            InputFileConfigurator ifc = new InputFileConfigurator(inFilePath, outFolderPath, dictPath, resName);
            AbstractCalculator ac;
            if(dictPath==null || dictPath.equals("") || dictPath.isEmpty())
                ac = new DefaultDictionaryCalc(ifc);
            else 
                ac = new CustomDictionaryCalc(ifc);
                t = new Text();
                t.setMetrics(ac.calculate());
                 try {
                //Whatever the file path is
                File f = new File(outFolderPath+"\\"+resName+".csv");
                FileOutputStream os = new FileOutputStream(f);
                OutputStreamWriter osw = new OutputStreamWriter(os);    
                Writer w = new BufferedWriter(osw);
                w.write("File is in the directory: "+", numWords:" + 
                        ", numTypes:" + ", TTR:" + ", lettersPerWord:" + 
                        ", numParagraphs:" + ", numSentences:" + 
                        ", wordsPerSentence:" + ", determiners:" + 
                        ", demonstratives:" + ", numPronouns:" + 
                        ", firstPersonPr:" + ", secondPersonPr:" + 
                        ", thirdPersonPr:" + ", conjuncts:" + ", connectives:" +
                        ", negations:" + ", future:" +"\n" +outFolderPath);
                w.write(t.getMetrics().toString());
                w.close();
                } catch (IOException e) {
                System.err.println("Problem writing to the file");
                }
            JOptionPane.showMessageDialog(this, "Calculation successful!");
            int q = JOptionPane.showConfirmDialog(this, "Do you want to analyze another text?", 
                    "Repeat analisys", JOptionPane.YES_NO_OPTION);
            if(q==1){
                JOptionPane.showMessageDialog(this, "GOODBYE");  
                System.exit(0);
            }
            }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error in calculating file - you "
                    + "must enter all the neccessary information!");
        }
    }//GEN-LAST:event_jbtnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTxtDictFilePath;
    private javax.swing.JTextField jTxtInputFilePath;
    private javax.swing.JTextField jTxtOutputFileName;
    private javax.swing.JTextField jTxtOutputFolderPath;
    private javax.swing.JButton jbtnCalculate;
    // End of variables declaration//GEN-END:variables
}
