/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import pack.AbstractCalculator;
import pack.CustomDictionaryCalc;
import pack.DefaultDictionaryCalc;
import pack.InputFileConfigurator;
import pack.Text;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Milica
 */
public class CalculatorForm extends JFrame {
    
    String inFilePath = null;
    String outFolderPath = null;
    String dictPath = null;
    String resName = null;
    /**
     * Creates new form CalculatorForm
     */
    public CalculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtOutputFileName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnCalculate = new javax.swing.JButton();
        InputFileButton = new javax.swing.JButton();
        OutputFolderButton = new javax.swing.JButton();
        DictionaryButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextInput = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextDictionary = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextOutputFolder = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Linguistic Metrics Calculator");
        setBackground(new java.awt.Color(204, 204, 255));
        setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        setForeground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Choose the input file you want to analyze:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Choose the output folder:");

        jTxtOutputFileName.setText(" ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Select a custom dictionary (optional):");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Enter the output file name:");

        jbtnCalculate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbtnCalculate.setText("Calculate!");
        jbtnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalculateActionPerformed(evt);
            }
        });

        InputFileButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InputFileButton.setText("Choose...");
        InputFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFileButtonActionPerformed(evt);
            }
        });

        OutputFolderButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OutputFolderButton.setText("Choose...");
        OutputFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputFolderButtonActionPerformed(evt);
            }
        });

        DictionaryButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DictionaryButton.setText("Choose...");
        DictionaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DictionaryButtonActionPerformed(evt);
            }
        });

        jTextInput.setEditable(false);
        jTextInput.setColumns(20);
        jTextInput.setRows(5);
        jScrollPane1.setViewportView(jTextInput);

        jTextDictionary.setEditable(false);
        jTextDictionary.setColumns(20);
        jTextDictionary.setRows(5);
        jScrollPane2.setViewportView(jTextDictionary);

        jTextOutputFolder.setEditable(false);
        jTextOutputFolder.setColumns(20);
        jTextOutputFolder.setRows(5);
        jScrollPane3.setViewportView(jTextOutputFolder);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtOutputFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputFileButton)
                            .addComponent(jbtnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OutputFolderButton)
                            .addComponent(DictionaryButton))
                        .addGap(32, 32, 32))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFileButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutputFolderButton)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DictionaryButton))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnCalculate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtOutputFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jbtnCalculateActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if(jTxtOutputFileName.getText()!=null)
            resName = jTxtOutputFileName.getText().trim();
        else resName = "results";
        try{
            InputFileConfigurator ifc = new InputFileConfigurator(inFilePath, outFolderPath, dictPath, resName);
            AbstractCalculator ac;
            if(dictPath==null || dictPath.equals("") || dictPath.isEmpty())
                ac = new DefaultDictionaryCalc(ifc);
            else 
                ac = new CustomDictionaryCalc(ifc);
            Text t = new Text();
            t.setMetrics(ac.calculate());
            PrintWriter pw = null;
            try {
                pw = new PrintWriter(new File(outFolderPath+"\\"+resName+".csv"));
            } catch (IOException e) {
            System.err.println("Problem writing to the file"+e.getMessage());
            }
            StringBuilder builder = new StringBuilder();
            String ColumnNamesList = "File is in the directory,numWord,numTypes,TTR,lettersPerWord"+
                ",numParagraphs,numSentences,wordsPerSentence,determiners,demonstratives,numPronouns"+
                ",firstPersonPr,secondPersonPr,thirdPersonPr,conjuncts,connectives,negations,future";
            
            builder.append(ColumnNamesList).append("\n");
            builder.append(outFolderPath).append(t.getMetrics().toString()).append("\n");
            pw.write(builder.toString());
            pw.close();
            
            JOptionPane.showMessageDialog(this, "Calculation successful!");
            int q = JOptionPane.showConfirmDialog(this, "Do you want to analyze another text?", 
                    "Repeat analysis", JOptionPane.YES_NO_OPTION);
            if(q==1){
                JOptionPane.showMessageDialog(this, "GOODBYE!");  
                System.exit(0);
            }
            }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error in calculating file - you "
                    + "must enter all the neccessary information!" +
                    "Error message: " + ex.getMessage());
        }
    }                                             

    private void InputFileButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
            inFilePath = fileChooser.getSelectedFile().toString();
            jTextInput.setText(inFilePath); 
        }
    }                                               

    private void OutputFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION){
            outFolderPath = fileChooser.getSelectedFile().toString();
            jTextOutputFolder.setText(outFolderPath);
        }
        else{
           jTextOutputFolder.setText("No selection!");
        }
    
    }                                                  

    private void DictionaryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION){
            dictPath = fileChooser.getSelectedFile().toString();
            jTextDictionary.setText(dictPath);
        }
    }                                                

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton DictionaryButton;
    private javax.swing.JButton InputFileButton;
    private javax.swing.JButton OutputFolderButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextDictionary;
    private javax.swing.JTextArea jTextInput;
    private javax.swing.JTextArea jTextOutputFolder;
    private javax.swing.JTextField jTxtOutputFileName;
    private javax.swing.JButton jbtnCalculate;
    // End of variables declaration                   
}
